config/routes.rb
Rails.application.routes.draw do

  resources :ldap_managers do
  collection do
    post "import_all"
    post "import_photo"
  end
end

  resources :users, only: [:index, :update]
  devise_for :admins
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :index
  root to: "index#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :ldap_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :username, presence: true, uniqueness: true

  before_validation :get_ldap_email
         #attr_accessor :username
   def get_ldap_email
      self.email = Devise::LDAP::Adapter.get_ldap_param(self.username,"mail").first
   end

   # use ldap uid as primary key
   before_validation :get_ldap_id
   def get_ldap_id
      params = Devise::LDAP::Adapter.get_ldap_param(self.username,"objectSid").first
      params_s = get_sid_string(params)
      self.id = params_s

   end

         # hack for remember_token
   def authenticatable_token
        Digest::SHA1.hexdigest(email)[0,29]
    end
before_validation :get_ldab_name
    def get_ldab_name
      self.name = Devise::LDAP::Adapter.get_ldap_param(self.username,"name").first
    end

    def get_sid_string(data)
        sid = data.unpack('b x nN V*')
        sid[1, 2] = Array[nil, b48_to_fixnum(sid[1], sid[2])]
        sid.delete("-")
      end

      B32 = 2**32

      def b48_to_fixnum(i16, i32)
        i32 + (i16 * B32)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :set_index, only: [:show]
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def update
    @user = User.find(params[:id])
  if @user.admin?
  	@user.update_attribute :admin, false
  else
    @user.update_attribute :admin, true
  end
  	redirect_to request.referrer, notice: "Профиль пользователя обновлен."
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="container">
<h1>Пользователи</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Имя</th>
      <th scope="col">Администратор</th>
      <th scope="col">Изменить роль</th>
    </tr>
  </thead>
  <tbody>
<% @users.each do |user| %>
<tr>
  <td><%= user.id %></td>
  <td><%= user.name %></td>
  <% if user.admin? %>
  <td>Да</td>
  <td><%= button_to "Забрать права", user_url(user), method: :put, class: "btn btn-warning" %></td>
  <% else %>
  <td>Нет</td>
  <td><%= button_to "Сделать Админом", user_url(user), method: :put, class: "btn btn-warning" %></td>
  <% end %>
</tr>
<% end %>
</div>