config/routes.rb
Rails.application.routes.draw do

  resources :ldap_managers do
  collection do
    post "import_all"
    post "import_photo"
  end
end

  resources :users, only: [:index, :update]
  devise_for :admins
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :index
  root to: "index#index"
end

app/models/ldap_manager.rb
class LdapManager < ApplicationRecord
end

app/controllers/ldap_managers_controller.rb
class LdapManagersController < ApplicationController
before_action :set_index, only: [:show, :edit, :update, :destroy]

  # GET /ldap_managers
  # GET /ldap_managers.json
  def index
    @directory = Index.all
    @index = Index.new
    @ldap_managers = LdapManager.all
    ldap = Net::LDAP.new	:host => "dc03.techlab.pp.ua",
                :port => 389,
                :encryption => :none,
                :base => "DC=dc,DC=techalb,DC=pp,DC=ua",
                :auth => {
                  :method => :simple,
                  :username => "directory",
                  :password => "P@ssw0rd"
                }
                filter = Net::LDAP::Filter.eq("sAMAccountName", "*")
                filter2 = Net::LDAP::Filter.eq("objectCategory", "organizationalPerson")
                joined_filter = Net::LDAP::Filter.join(filter, filter2)
                treebase = "OU=Office_Users,DC=office,DC=parallel,DC=ua"
    @ldusers = ldap.search(:base => treebase, :filter => joined_filter, :return_result => true)
  end

  def create
      @index = Index.new(index_params)
      respond_to do |format|
        if @index.save
          format.html { redirect_to request.referrer, notice: 'Учетная запись пользователя создана успешно.' }
          format.json { render :show, status: :created, location: @index }
        else
          format.html { render :new }
          format.json { render json: @index.errors, status: :unprocessable_entity }
        end
      end
    end

    def import_all
	ldap = Net::LDAP.new        :host => "dc03.techlab.pp.ua",
                :port => 389,
                :encryption => :none,
                :base => "DC=test,DC=techlab,DC=pp,DC=ua",
                :auth => {
                  :method => :simple,
                  :username => "directory",
                  :password => "P@ssw0rd"
                }
                filter = Net::LDAP::Filter.eq("sAMAccountName", "*")
                filter2 = Net::LDAP::Filter.eq("objectCategory", "organizationalPerson")
                joined_filter = Net::LDAP::Filter.join(filter, filter2)
                treebase = "OU=test,DC=techlab,DC=pp,DC=ua"
    @ldusers = ldap.search(:base => treebase, :filter => joined_filter, :return_result => true)
      @ldusers.each do |ldap|
                  pluton_worker = Index.new
                  pluton_worker.name = ldapadap(ldap, :name)
                  pluton_worker.givenName = ldapadap(ldap, :givenName)
                  pluton_worker.sAMAccountName = ldapadap(ldap, :sAMAccountName)
                  pluton_worker.sn = ldapadap(ldap, :sn)
                  pluton_worker.displayName = ldapadap(ldap, :displayName)
                  pluton_worker.description = ldapadap(ldap, :description)
                  pluton_worker.physicalDeliveryOfficeName = ldapadap(ldap, :physicalDeliveryOfficeName)
                  pluton_worker.telephoneNumber = ldapadap(ldap, :telephoneNumber)
                  pluton_worker.mail = ldapadap(ldap, :mail)
                  pluton_worker.title = ldapadap(ldap, :title)
                  pluton_worker.department = ldapadap(ldap, :department)
                  pluton_worker.company = ldapadap(ldap, :company)
                  pluton_worker.ipphone = ldapadap(ldap, :ipphone)
                  pluton_worker.mobile = ldapadap(ldap, :mobile)
                  pluton_worker.company = ldapadap(ldap, :company)
                  pluton_worker.homephone = ldapadap(ldap, :homephone)
                  pluton_worker.cloudUser = false
                  pluton_worker.usbUser = false
                  pluton_worker.userit = false
                  pluton_worker.registered = true
                  pluton_worker.photo = '/public/images/avatar/'+ldapadap(ldap, :sAMAccountName)+'.jpg'
                  pluton_worker.save
                end
      redirect_to request.referrer, notice: "Импорт завершен."
    end

    def import_photo
	ldap = Net::LDAP.new        :host => "dc03.techlab.pp.ua",
                :port => 389,
                :encryption => :none,
                :base => "DC=office,DC=techlab,DC=pp,DC=ua",
                :auth => {
                  :method => :simple,
                  :username => "directory",
                  :password => ""
                }
                filter = Net::LDAP::Filter.eq("sAMAccountName", "*")
                filter2 = Net::LDAP::Filter.eq("objectCategory", "organizationalPerson")
                joined_filter = Net::LDAP::Filter.join(filter, filter2)
                treebase = "OU=Office_Users,DC=office,DC=parallel,DC=ua"
    @ldusers = ldap.search(:base => treebase, :filter => joined_filter, :return_result => true)
      @ldusers.each do |data|
        [:thumbnailphoto, :jpegphoto, :photo].each do |photo_key|
          if data.attribute_names.include?(photo_key)
            photo_save(ldapadap(data, :sAMAccountName),data.thumbnailPhoto[0])
          end
        end
      end
      redirect_to request.referrer, notice: 'Фотографии загружены'
    end
    private
    # Use callbacks to share common setup or constraints between actions.
    def ldapConnector
      ldap = Net::LDAP.new        :host => "dc03.techalab.pp.ua",
                :port => 389,
                :encryption => :none,
                :base => "DC=test,DC=techlab,DC=pp,DC=ua",
                :auth => {
                  :method => :simple,
                  :username => "directory",
                  :password => ""
                }
                filter = Net::LDAP::Filter.eq("sAMAccountName", "*")
                filter2 = Net::LDAP::Filter.eq("objectCategory", "organizationalPerson")
                joined_filter = Net::LDAP::Filter.join(filter, filter2)
                treebase = "OU=Office_Users,DC=office,DC=parallel,DC=ua"
    @ldusers = ldap.search(:base => treebase, :filter => joined_filter, :return_result => true)
      return ldusers
    end

    def set_index
      @index = Index.find(params[:id])
    end

    def photo_save(name,data)
        File.open('public/images/avatars/'+name+'.jpg', 'wb') { |f| f.write(data) }
    end

    def ldapadap(data,key)
      begin
        data[key].to_s.delete('"[]"')
      rescue
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def index_params
      params.require(:name).permit(:name, :givenName, :sn, :sAMAccountName, :displayName, :description, :physicalDeliveryOfficeName, :telephoneNumber, :mail, :title, :department, :company, :ipphone, :mobile, :homephone, :photo, :cloudUser, :usbUser, :userit)
    end
end

app/helpers/ldap_managers_helper.rb
module LdapManagersHelper
  def ldapadap(data,key)
    begin
      data[key].to_s.delete('"[]"')
    rescue
    end
  end

  def matching(users,ldap, match)
    users.where(:sAMAccountName => ldap.sAMAccountName.to_s.delete('"[]"')).map { |user|
      if user[match] == ldap[match].to_s.delete('"[]"')
      else
        return [%w(danger), user[match]]
      end
    }
  end
  
end

app/views/ldap_managers/_form.html.erb
<%= form_with(model: ldap_manager, local: true) do |form| %>
  <% if ldap_manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ldap_manager.errors.count, "error") %> prohibited this ldap_manager from being saved:</h2>

      <ul>
      <% ldap_manager.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ldap_managers/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', index: @index_index_path %>

<%= link_to 'Show', @index %> |
<%= link_to 'Back', index_index_path %>

app/views/ldap_managers/index.html.erb
<h1>Сравнение записей АД и Справочника</h1>

<div>
  <%= button_to "Имортировать всех пользователей", import_all_ldap_managers_path(:all), :action => 'import_all', :class => 'btn btn-danger in-line', data: { confirm:'Вы уверены, что хотите имортировать всех пользователей? Новые пользователи будут добавлены к существующим!' } %>
  <%= button_to "Импортировать фотографии", import_photo_ldap_managers_path, :action => 'import_photo', :class => 'btn btn-danger in-line mrgin' %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">sn</th>
      <th scope="col">displayName</th>
      <th scope="col">Mail</th>
      <th scope="col">Room</th>
      <th scope="col">Phone</th>
      <th scope="col">Title</th>
      <th scope="col">Department</th>
      <th scope="col">City phone</th>
      <th scope="col">Corp phone</th>
      <th scope="col">Priv phone</th>
    </tr>
  </thead>
  <tbody>
    <% if @ldusers.present? %>  <!-- Check if @ldusers is present -->
      <% @ldusers.each do |ldap| %>
        <% @res = :danger %>
        <% if @directory.present? %>  <!-- Check if @directory is present -->
          <% @directory.each do |dir| %>
            <% if ldapadap(ldap, :sAMAccountName) == dir.sAMAccountName %>
              <% @res = :default %>
            <% end %>
          <% end %>
        <% end %>
        
        <tr class="<%= @res %>">
          <% @res = :danger %>

          <td class="<%= ldapadap(matching(@directory, ldap, :name), 0) %>">
            <%= ldapadap(ldap, :name) %><br><%= ldapadap(matching(@directory, ldap, :name), 1) %>
          </td>
          <td><%= ldapadap(ldap, :sn) %></td>
          <td class="<%= ldapadap(matching(@directory, ldap, :displayName), 0) %>">
            <%= ldapadap(ldap, :displayName) %><br><%= ldapadap(matching(@directory, ldap, :displayName), 1) %>
          </td>
          <td class="<%= ldapadap(matching(@directory, ldap, :mail), 0) %>">
            <%= mail_to ldapadap(ldap, :mail) %><br><%= ldapadap(matching(@directory, ldap, :mail), 1) %>
          </td>
          <td class="<%= ldapadap(matching(@directory, ldap, :physicalDeliveryOfficeName), 0) %>">
            <%= ldapadap(ldap, :physicalDeliveryOfficeName) %><br><%= ldapadap(matching(@directory, ldap, :physicalDeliveryOfficeName), 1) %>
          </td>
          <td class="<%= ldapadap(matching(@directory, ldap, :telephoneNumber), 0) %>">
            <%= ldapadap(ldap, :telephonenumber) %><br><%= ldapadap(matching(@directory, ldap, :telephoneNumber), 1) %>
          </td>
          <td class="<%= ldapadap(matching(@directory, ldap, :title), 0) %>">
            <%= ldapadap(ldap, :title) %><br><%= ldapadap(matching(@directory, ldap, :title), 1) %>
          </td>
          <td class="<%= ldapadap(matching(@directory, ldap, :department), 0) %>">
            <%= ldapadap(ldap, :department) %><br><%= ldapadap(matching(@directory, ldap, :department), 1) %>
          </td>
          <td class="<%= ldapadap(matching(@directory, ldap, :ipphone), 0) %>">
            <%= ldapadap(ldap, :ipphone) %><br><%= ldapadap(matching(@directory, ldap, :ipphone), 1) %>
          </td>
          <td class="<%= ldapadap(matching(@directory, ldap, :mobile), 0) %>">
            <%= ldapadap(ldap, :mobile) %><br><%= ldapadap(matching(@directory, ldap, :mobile), 1) %>
          </td>
          <td class="<%= ldapadap(matching(@directory, ldap, :homephone), 0) %>">
            <%= ldapadap(ldap, :homephone) %><br><%= ldapadap(matching(@directory, ldap, :homephone), 1) %>
          </td>
          <%= form_for @index, url: { action: "create" } do |f| %>
            <%= hidden_field :name, :name, value: ldapadap(ldap, :name) %>
            <%= hidden_field :name, :sAMAccountName, value: ldapadap(ldap, :sAMAccountName) %>
            <%= hidden_field :name, :sn, value: ldapadap(ldap, :sn) %>
            <%= hidden_field :name, :mail, value: ldapadap(ldap, :mail) %>
            <%= hidden_field :name, :displayName, value: ldapadap(ldap, :displayName) %>
            <%= hidden_field :name, :physicalDeliveryOfficeName, value: ldapadap(ldap, :physicalDeliveryOfficeName) %>
            <%= hidden_field :name, :telephoneNumber, value: ldapadap(ldap, :telephoneNumber) %>
            <%= hidden_field :name, :title, value: ldapadap(ldap, :title) %>
            <%= hidden_field :name, :department, value: ldapadap(ldap, :department) %>
            <%= hidden_field :name, :ipphone, value: ldapadap(ldap, :ipphone) %>
            <%= hidden_field :name, :mobile, value: ldapadap(ldap, :mobile) %>
            <%= hidden_field :name, :homephone, value: ldapadap(ldap, :homephone) %>
            <%= hidden_field :name, :registered, value: true %>
            <td><%= f.submit "Добавить в справочник", class: "btn btn-primary" %></td>
          <% end %>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="11">Нет данных для отображения</td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/ldap_managers/new.html.erb
<h1>New Ldap Manager</h1>

<%= render 'form', ldap_manager: @ldap_manager %>

<%= link_to 'Back', ldap_managers_path %>

app/views/ldap_managers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_ldap_manager_path(@ldap_manager) %> |
<%= link_to 'Back', ldap_managers_path %>